Cypress.Commands.add('loginUserPasswordInvalid', (username, password) => {
  cy.visit(Cypress.env('urls').baseUrl)
  cy.wait(2000)
  cy.elementExists('#onetrust-accept-btn-handler').click()
  cy.wait(2000)
  cy.get('input[name="UserName"]').type(username, { log: false })
  cy.get('input[name="Password"]').first().type(password, { log: false })
  cy.get('#btnSubmit').click()
  cy.get('.alert-login-error-text').should('have.text', Cypress.env('login').msg_login_or_password_invalid)
})

Cypress.Commands.add('loginService', (username, password) => {
  cy.visit(Cypress.env('urls').baseUrl)
  cy.wait(3000)
  cy.elementExists('#onetrust-accept-btn-handler').click()
  cy.wait(1000)
  cy.get('input[name="UserName"]').type(username, { log: false })
  cy.get('input[name="Password"]').first().type(password, { log: false })
  cy.get('#btnSubmit').click()
  cy.wait(2000)
  cy.elementExists('button[data-value="yes"]').click()
  cy.elementExists('button[data-testid="ug-custom-button-4"]').click()
  cy.get('.col-xs-10').should('be.visible')
  cy.get('.col-xs-10').should('have.text', Cypress.env('login').lbls_home_widget)
})

Cypress.Commands.add('logoutService', () => {
  cy.elementExists('#top-bar-avatar-picture').click()
  cy.get('#sign-out-link').click()
  cy.elementExists('#btnSubmit')
})

Cypress.Commands.add('loginServiceSSO', (username, userNameSso, passwordSso) => {
  cy.visit(Cypress.env('urls').baseUrl)
  cy.wait(3000)
  cy.elementExists('#onetrust-accept-btn-handler').click()
  cy.wait(1000)
  cy.get('input[name="UserName"]').first().type(username, { log: false })
  cy.get('#btnSubmitSso').click()
  cy.wait(10000)
  cy.elementExists('.banner-close-button ot-close-icon').click()
  cy.get('#email_signin').first().type(userNameSso, { log: false })
  cy.get('#btn-next').click()
  cy.elementExists('#password_signin').type(passwordSso, { log: false })
  cy.elementExists('#btn-signin').click()
  cy.wait(5000)
  cy.elementExists('button[data-value="yes"]').click()
  cy.get('.col-xs-10').should('be.visible')
})

Cypress.Commands.add('loginServiceNew', (username, password) => {
  cy.visit(Cypress.env('urls').baseUrl)
  cy.wait(3000)
  cy.elementExists('#onetrust-accept-btn-handler').click()
  cy.wait(1000)
  cy.get('input[name="UserName"]').first().type(username, { log: false })
  cy.get('#btnSubmitSso').click()
  cy.wait(1000)
  cy.get('input[name="Password"]').first().type(password, { log: false })
  cy.get('#btnSubmit').click()
  cy.wait(5000)
  cy.elementExists('button[data-value="yes"]').click()
  cy.get('.col-xs-10').should('be.visible')
})

Cypress.Commands.add('validLoginType', (username, password) => {
  cy.visit(Cypress.env('urls').baseUrl)
  cy.wait(3000)
  cy.get('body').then(($body) => {
    if ($body.find('#btnSubmitSso').length > 0) {
      cy.elementExists('#onetrust-accept-btn-handler').click()
      cy.wait(1000)
      cy.get('input[name="UserName"]').first().type(username, { log: false })
      cy.get('#btnSubmitSso').click()
      cy.wait(1000)
      cy.get('input[name="Password"]').first().type(password, { log: false })
      cy.get('#btnSubmit').click()
      cy.wait(5000)
      cy.elementExists('button[data-value="yes"]').click()
      cy.get('.col-xs-10').should('be.visible')
      cy.log('Login SSO With Sucess')
    } else {
      cy.elementExists('#onetrust-accept-btn-handler').click()
      cy.wait(2000)
      cy.get('input[name="UserName"]').type(username, { log: false })
      cy.get('input[name="Password"]').first().type(password, { log: false })
      cy.get('#btnSubmit').click()
      cy.log('Login classic With Sucess')
    }
  })
})